server:
  port: 8080

spring:
  application:
    name: common

  datasource:
    url: jdbc:postgresql://localhost:5432/citizix_db
    username: citizix_user
    password: S3cret
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: trace

otel:
  traces:
    exporter: logging
    exporter.endpoint: http://localhost:4317
  metrics:
    exporter: none
  propagators: tracecontext
  instrumentation:
    hibernate:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
    logs:
        endpoint: http://localhost:4318/v1/logs
  tracing:
    enabled: true
    propagation:
      type: w3c
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s


#    tags:
#      department: ${SERVICE_DEPARTMENT:software}
#      team: ${SERVICE_TEAM:greeting}
#      service: ${spring.application.name}
#      env: ${SERVICE_ENV:dev}
#      region: ${SERVICE_REGION:europe-west1}
#      instance.id: ${SERVICE_INSTANCE_ID:dasdasdsadasd}