server:
  port: 8082

svc:
  gamma:
    endpoint: http://localhost:8083
    api:
      users: /v3/users
      exception: /v3/users/exception

spring:
  application:
    name: beta-svc

  datasource:
    url: jdbc:postgresql://localhost:5432/citizix_db
    username: citizix_user
    password: S3cret
    driver-class-name: org.postgresql.Driver
