server:
  port: 8083

spring:
  application:
    name: gamma-svc

  datasource:
    url: jdbc:postgresql://localhost:5432/citizix_db
    username: citizix_user
    password: S3cret
    driver-class-name: org.postgresql.Driver