server:
  port: 8081

svc:
  beta:
    endpoint: http://localhost:8082
    api:
      users: /v2/users
      beta: /v2/users/exception/beta
      gamma: /v2/users/exception/gamma

spring:
  application:
    name: alpha-svc
  datasource:
    url: jdbc:postgresql://localhost:5432/citizix_db
    username: citizix_user
    password: S3cret
    driver-class-name: org.postgresql.Driver
